apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-github-8oix2wzga9lni
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-github-8oix2wzga9lni
    app.kubernetes.io/part-of: application-github-766d20k1a94en
  name: component-github-8oix2wzga9lni
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-github-8oix2wzga9lni
status:
  loadBalancer: {}
